import { EXPO_PUBLIC_API_URL, EXPO_PUBLIC_GOOGLE_MAPS_API_KEY, EXPO_PUBLIC_GEOLOCATION_API_KEY } from '@env';

export const API_URL = EXPO_PUBLIC_API_URL || '';
export const GOOGLE_MAPS_API_KEY = EXPO_PUBLIC_GOOGLE_MAPS_API_KEY || '';
export const GEOLOCATION_API_KEY = EXPO_PUBLIC_GEOLOCATION_API_KEY || '';